# Generated by Django 5.0 on 2024-02-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_venuecard_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuecard',
            old_name='image_url',
            new_name='location_link',
        ),
        migrations.RemoveField(
            model_name='venuecard',
            name='link',
        ),
        migrations.RemoveField(
            model_name='venuecard',
            name='location',
        ),
        migrations.AddField(
            model_name='venuecard',
            name='images',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
