# Generated by Django 5.0 on 2024-02-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_venuecard_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='venuecards/')),
            ],
        ),
        migrations.RemoveField(
            model_name='venuecard',
            name='images',
        ),
        migrations.AddField(
            model_name='venuecard',
            name='images',
            field=models.ManyToManyField(blank=True, to='posts.image'),
        ),
    ]
