# Generated by Django 5.0 on 2024-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_image_remove_venuecard_images_venuecard_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuecard',
            name='images',
        ),
        migrations.AddField(
            model_name='venuecard',
            name='images',
            field=models.FileField(default=' ', upload_to=''),
        ),
    ]
